on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - uses: DeLaGuardo/setup-clojure@master
      with:
        lein: 2.9.4
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm i 
    - run: lein cljsbuild once min
    - run: |
        git config --global user.name "Renato Alencar"
        git config --global user.email "renatoalencar.73@gmail.com"
        git add -A
        git commit -m 'GH Actions build'
        git push origin master
